version: '3'

services:
  app:
    container_name: setup-nodejs
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./:/src/main/server/
    environment:
      - PORT=3000
    ports:
      - 3000:3000